<a href="https://colab.research.google.com/github/IshanJain1211/Deep-Learning/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [ ]:
my_list=[[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr1=np.random.rand(3,4)
arr1

array([[0.15908239, 0.81709318, 0.27697221, 0.11816539],
       [0.0969891 , 0.64388047, 0.10248448, 0.42840203],
       [0.53270542, 0.76874911, 0.71265253, 0.07264417]])

Tensors same as numpy array but GPU use kr skte hain and Visualization mein helpful Designed for deep learning



In [ ]:
tensor_2d=torch.randn(3)
tensor_2d

tensor([-0.2525, -0.5329, -1.3340])

In [ ]:
tensor_3d=torch.zeros(3,4,5)
tensor_3d

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
tens=torch.tensor(arr1)
tens
tens.dtype

torch.float64

In [ ]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and View
my_torch=my_torch.reshape(2,5)
my_torch#agar yahan 2,6 likhta to error aa jaata

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#We can reshape when we dont know the no. of items using -1

mytorch=torch.arange(10)
mytorch=mytorch.reshape(-1,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3=torch.arange(20)
my_torch4=my_torch3.view(5,4)
my_torch4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
my_torch4[1][2]=34
my_torch4 #yahan update kiya to upar bhi update ho gay

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 34,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
my_torch3[10]#tensor(10)

tensor(10)

In [ ]:
my_torch4[:,1]

tensor([ 1,  5,  9, 13, 17])

In [ ]:
my_torch4[:3,:2]

tensor([[0, 1],
        [4, 5],
        [8, 9]])

Math Operation for tensors

In [ ]:
my_a=torch.tensor([1,2,3,4])
my_b=torch.tensor([5,6,7,8])
my_a+my_b

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add(my_a,my_b)#Addition Longhand = my_a.add(my_b) aisa sb mul,sub,div,rem mein kr skte hain

tensor([ 6,  8, 10, 12])

In [ ]:
my_b-my_a

tensor([4, 4, 4, 4])

In [ ]:
torch.sub(my_a,my_b)

tensor([-4, -4, -4, -4])

In [ ]:
print(my_b/my_a)
my_a*my_b

tensor([5.0000, 3.0000, 2.3333, 2.0000])


tensor([ 5, 12, 21, 32])

In [ ]:
print(torch.div(my_b,my_a))#Divisor
print(torch.remainder(my_b,my_a))#Remainder=my_b%my_a
torch.mul(my_b,my_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([0, 0, 1, 0])


tensor([ 5, 12, 21, 32])

In [ ]:
print(torch.pow(my_b,my_a))
print(my_b**my_a)

tensor([   5,   36,  343, 4096])
tensor([   5,   36,  343, 4096])


In [ ]:
my_b.add_(my_a)#reasssigned using _ before the brackets = my_b+=my_a

tensor([16, 20, 24, 28])

In [ ]:
my_b

tensor([16, 20, 24, 28])